### ISSUE TITLE
OAuthService issue

### ISSUE THREAD

**Issue by d13cd2** [citrix/ShareFile-NET#16]
Hi.  

We're getting a strange error when trying to create a new OAuthService.
We're getting the compilation error:
 The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes'.	

The error goes away if we remove "portable-net45+win8" from the frameworks in the project.json but unfortunately  we need to keep this in for another part of the project.

Any ideas?

Thanks

**Comment by rgmills** [comment]
Would you be able to share a small sample repro that we can look at?  Also, are you consuming via NuGet or building from source and including those binaries directly?

**Comment by d13cd2** [comment]
We are using Nuget to get it.  
Currently the code is literally copy and pasted from your sample code and it's the Password Authentication method that causing the issue.  Then anything that references the oAuthService object.

This is what is in our project.json:
```
"version": "1.0.0-*",
    "buildOptions": {
        "emitEntryPoint": true
    },
"dependencies": {
        "MailKit": "1.4.0",
        "Microsoft.Extensions.Configuration": "1.0.0",
        "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
        "Microsoft.Extensions.Configuration.Json": "1.0.0",
        "Microsoft.Extensions.Logging": "1.0.0",
        "Microsoft.Extensions.Logging.Abstractions": "1.0.0",
        "Microsoft.Extensions.Logging.Console": "1.0.0",
        "Microsoft.Extensions.PlatformAbstractions": "1.0.0",
        "Microsoft.NETCore.App": "1.0.0",
        "MimeKit": "1.4.0",
        "OurProject.BusinessLogic": "1.0.0-*",
        "OurProject.Data": "1.0.0-*",
        "ShareFile.Api.Client.StrongName": "3.0.33",
        "System.Data.Common": "4.1.0",
        "System.Data.SqlClient": "4.1.0",
        "System.Net.Requests": "4.0.11",
        "System.Runtime": "4.1.0"
    },

    "frameworks": {
        "netcoreapp1.0": {
            "imports": [
                "dotnet5.6",
                "dnxcore50",
                "portable-net45+win8"
            ]
        }
    }
```

**Comment by rgmills** [comment]
Thanks, we'll take a look and see what's going on. I also had a member of our team publish a newer version which has a netstandard 1.3 target. While we take a look, if you can upgrade to the latest (3.3.0) hopefully that will resolve. If not, we'll make whatever changes we need a get an updated version out for you.

**Comment by d13cd2** [comment]
Yes that seems to have fixed it.  Thanks!

**Comment by rgmills** [comment]
Fantastic!
