### ISSUE TITLE
Check Out and Checking

### ISSUE THREAD

**Issue by shahshyam** [citrix/ShareFile-NET#18]
I am trying to checking and Checkout file from desktop application using C#. According ShareFiles API documentation, It allow user to checkin and checkout in SharePoint server. However, Sync tool of ShareFile provides feature of Checking and Checkout.  I tried using this code but not able to use in C# console application or Desktop Apps.  Is any way to Checkout or Checkin in Console or Desktop Apps ?

**Comment by rgmills** [comment]
Hi @shahshyam , there is a way with our API however that is not currently available publicly (I thought we had lifted those restrictions).  I've raised an internal issue to make it available.  I'll follow up once we get the required changes in.

**Comment by shahshyam** [comment]
Hi, I have got some private url for item locking and unlocking. I want to implement that url in your git hub repository code but unable to do so. Can you please help me to implement . I got filelock and fileunlock , discard, lockinfo and lockupdate in non sharepoint Environment

**Comment by rgmills** [comment]
@shahshyam We've done the clean up work we've needed to do to make this API public.  If you're using the NuGet package, https://www.nuget.org/packages/ShareFile.Api.Client/ it should now have the latest.  The latest source is available as well.

Sorry for the delay.

**Comment by shahshyam** [comment]
Hi
File unlocking is not working . I am trying to use following code .
sfClient.FileLock.DeleteByItem(Item.url, FileLock.LockId);

Where item.url is url of file already file lock and lock id .

**Comment by rgmills** [comment]
Hi @shahshyam , could you provide any error messages you are receiving? Is the authenticated user the lock owner?

**Comment by shahshyam** [comment]
I did not get any error . I just execute sfClient.FileLock.DeleteByItem(Item.url, FileLock.LockId); and execute successful. authenticated user  is the lock owner. It works when i just execute using Creating web request 

 public static void Unlock(OAuth2Token token,string lockId)
        {
            string fileId = "fi1609ef-63cb-b08f-b1b5-604228626d66";
            String uri = string.Format("https://{0}/sf/v3/Items({1})/FileLock({2})", ShareFileV3Sample.GetHostname(token), fileId,lockId);
            Console.WriteLine(uri);

            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(uri);
            ShareFileV3Sample.addAuthorizationHeader(request, token);

            Dictionary<string, object> folder = new Dictionary<string, object>();
            folder.Add("id",fileId);
            folder.Add("lockid",lockId);
           
            string json = JsonConvert.SerializeObject(folder);

            Console.WriteLine(json);

            request.Method = "POST";
            request.ContentType = "application/json";
            using (var writer = new StreamWriter(request.GetRequestStream()))
            {
                writer.Write(json);
            }

            
            HttpWebResponse response = (HttpWebResponse)request.GetResponse();
            Console.WriteLine(response.StatusCode);
            using (var reader = new StreamReader(response.GetResponseStream()))
            {
                String body = reader.ReadToEnd();
                JObject newFolder = JObject.Parse(body);
                Console.WriteLine("Created Folder: " + newFolder["Id"]);
                lockId = newFolder["Id"].ToString();
            }
            
        }

**Comment by shahshyam** [comment]
Above code is work  for only individual account . Now,  I am trying to use company account. not able to work. it gives not allowed . The remote server returned an error: (405) Method Not Allowed.

**Comment by shahshyam** [comment]
Working, thanks for support
