### ISSUE TITLE
FavoriteFolder is not working

### ISSUE THREAD

**Issue by shahshyam** [citrix/ShareFile-NET#21]
I am using your git repository code . I am pulling favorite folder from api but it does not give response. it throw exception.

My account detail :- company account
code=

 var account = sfClient.Accounts.Get(null).Execute();
            var favoritefolderlist=sfClient.FavoriteFolders.GetByUser(account.url).Execute();

**Comment by rgmills** [comment]
Hi @shahshyam to fetch favorite folders for the current user, you'd do the following:

```
var user = sfClient.Users.Get().Execute();
var favoriteFolders = sfClient.FavoriteFolders.GetByUser(user.url).Execute();
```

The intended url should be that of the `user` not the `account`.

Hope this helps!

**Comment by shahshyam** [comment]
Thanks for your help. It is working .

**Comment by bpw320** [comment]
get error:  ShareFile.Api.Client.Exceptions.ODataException: 'Authorization failed: FavoriteService.Get'
