### ISSUE TITLE
Unable to download Doc file from ShareFile using API

### ISSUE THREAD

**Issue by shahshyam** [citrix/ShareFile-NET#23]
I am using code 
var downloader = sfClient.GetAsyncFileDownloader(itemToDownload);
  using(var fileStream = File.Open(@"C:\test\newImage.png", FileMode.OpenOrCreate))
  {
    await downloader.DownloadToAsync(fileStream);
  }

I am getting exception : task was cancelled exception . 
I am using latest version of DLL (Relase date : Dec 04, 2016

**Comment by rgmills** [comment]
Thanks for raising the issue, will take a look. In the meantime, would you be able to provide a bit more information for me?

- What is the size of the file?
- Was the file recently uploaded (I.e you're performing a sync type behavior upload and immediately download?
- Do you know if you are uploading to an on premises StorageZone or ShareFile hosted StorageZone?

**Comment by shahshyam** [comment]
Hi
Regarding your question .
the file is small about 56 KB , docs extension
i uploaded 1 hour ago and then try to download .
![image](https://cloud.githubusercontent.com/assets/4408930/20925668/3d313320-bbe0-11e6-8fae-c2ace0d3ea74.png)

I am using cloud version with company account

**Comment by shahshyam** [comment]
Hi 
Did you get time to resolve File downloading issue, ? is any way to download file from ShareFile ? I need emergency . I am waiting for your reply.

**Comment by rgmills** [comment]
Hi, I tried to reproduce the error however I am unable to. Do you have a small isolated reproduction of the error that you could share? Did this happen after updating to the latest version of the SDK?

**Comment by shahshyam** [comment]
I was not used  its previous version. It is my first time .  I am integrating in Com addin where I want to download .docx extension file. 

 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at ShareFile.Api.Client.Requests.Executors.AsyncRequestExecutor.<SendAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at ShareFile.Api.Client.Requests.Providers.AsyncRequestProvider.<ExecuteRequestAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

Can we please provide me your skype id show that i will contact as per your available time  ? I am waiting for your reply

**Comment by shahshyam** [comment]
it is working form window form application

**Comment by rgmills** [comment]
@shahshyam wanted to follow up on this, are you still facing the issues?  Sorry, I had PTO and forgot to check in once I came back.

**Comment by shahshyam** [comment]
Hi
I am still getting issue . It was working if i  am using webrequest for download .
