### ISSUE TITLE
Get Sharelink of uploaded FILE in ShareFile

### ISSUE THREAD

**Issue by sumeshkp18** [citrix/ShareFile-NET#30]
Hi, 
Anybody know how to get the public share link of uploaded file in Sharefile?

I can access the folder with this link https://[subdoamin].sharefile.com/f/foada1a1-d54d-4c8f-83d4-5a4afcde242e

same like we have share link to a file https://[subdomain].sharefile.com/d-se8c61584fe94c278

Can anybody help to get these share links by the sharefile Id using ShareFile-NET library?

Thanks in advance

**Comment by tigersai** [comment]
Please refer to http://api.sharefile.com/rest/docs/resource.aspx?name=Shares
For ShareFile dotnet SDK, please refer to https://github.com/citrix/ShareFile-NET#accessing-a-share

You can get list of shares created by the authenticated user

GET https://account.sf-api.com/sf/v3/Shares

Or retrieve specific share with passing ShareID

GET https://account.sf-api.com/sf/v3/Shares(id)

You can also create a new share link using

POST https://account.sf-api.com/sf/v3/Shares?notify=false
{ 
"ShareType":"Send", 
"Title":"Sample Send Share", 
"Items": [ { "Id":"itemid01" }, { "Id":"itemid02" } ], 
"Recipients":[ { "User": { "Id":"userid" } }, { "User": { "Email": "user@email" } } ], 
"ExpirationDate": "2013-07-23", 
"RequireLogin": false, 
"RequireUserInfo": false, 
"MaxDownloads": -1, 
"UsesStreamIDs": false
} 

Share link can be found in Uri in response body.

Please feel free to let me know if any question.

**Comment by vannesabids** [comment]
Hey! 
Do you know how to get the Sharable files without their versions??

**Comment by EmmaGCitrix** [comment]
Hi, can you open a new issue for this? And please include more information. I'm not exactly sure what you mean.
Link to our API docs for Share: https://api.sharefile.com/docs/resource?name=Shares
