### ISSUE TITLE
How to Check out or Check in the document with this sdk?

### ISSUE THREAD

**Issue by hezongzhan** [citrix/ShareFile-NET#32]
Hi,
I want to check out or check in a document with this sdk.
How to do this?

thank you

**Comment by NickNichollsCitrix** [comment]
If you have an instance of `ShareFileClient` and the ShareFile url for the item, then you can check in a document with
`await ShareFileClient.Items.CheckIn(itemUrl).ExecuteAsync();`

Check out looks like
`await ShareFileClient.Items.CheckOut(itemUrl).ExecuteAsync();`

**Comment by hezongzhan** [comment]
Hi,
 I have try to use the "await ShareFileClient.Items.CheckOut(itemUrl).ExecuteAsync();" to check out the document. But it seems not work.
Do you have any suggestions?

![image](https://user-images.githubusercontent.com/43662644/46242355-b0305d00-c3fa-11e8-9ca5-e9f3cf9b6af1.png)

**Comment by NickNichollsCitrix** [comment]
That CheckIn API only works with the SharePoint connector.
In your case you will want to use the FileLock APIs

Check in:
`ShareFileClient.FileLock.DeleteByItem(file.GetObjectUri(), file.FileLockInfo.LockId).ExecuteAsync()`

Discard:
`ShareFileClient.FileLock.Discard(file.GetObjectUri(), file.FileLockInfo.LockId).ExecuteAsync()`

Check out:
```
ShareFileClient.FileLock.CreateByItem(
    file.url,
    new FileLock
    {
        Owner = currentUser,
        ExpirationTimeInMinutes = expirationTime
    })
    .ExecuteAsync()
```

**Comment by hezongzhan** [comment]
I have try to use the ShareFileClient.FileLock.CreateByItem to check out the file.
But it can not check out secussful.
The error info is "FileLock owner is not authenticated user".
It seems that the Owner is not right.

this is my Owner info code:
 var principalTemp = new Principal
            {
                Name = "Johnny",
                Email = user.Username,
                Username = user.Username,
                Domain = user.Subdomain
            };

            await sfClient.FileLock.CreateByItem(uploadedFile.url,
    new FileLock
    {
        Owner = principalTemp,
        ExpirationTimeInMinutes = 28800
    })
    .ExecuteAsync();

**How to get the right Owner info to set ?**

![image](https://user-images.githubusercontent.com/43662644/46597387-7bb35400-cb12-11e8-8dee-84a7bcbe83a3.png)

**Comment by hezongzhan** [comment]
After use the right current user , the FileLock sucessful now.
thank you 

I still have another problem about upload file.
When I upload the download file to overwrite the already exist file on sharefile, I use the interface "uploader.UploadAsync", But the file on the sharefile has not been overwrite. It create a new version of the file.

If I want to overwrite the exist file on the sharefile.
Do you have any suggestions?

this is my code:
var file = System.IO.File.Open("928.txt", FileMode.OpenOrCreate);
            var uploadRequest = new UploadSpecificationRequest
            {
                Method = 0,
                FileName = "928.txt",
                FileSize = file.Length,
                Details = "Sample details",
                Parent = destinationFolder.url,
                Overwrite = true
            };
            var uploader = sfClient.GetAsyncFileUploader(uploadRequest, file);
            var uploadResponse = await uploader.UploadAsync();


![image](https://user-images.githubusercontent.com/43662644/46649240-ed4ed900-cbca-11e8-8b61-34468b85cbb3.png)

**Comment by NickNichollsCitrix** [comment]
Creating a new version is the recommended approach and it is what all of our tools will do.

If you must delete the previous versions, you can do something like:
```
// Get all versions
var versions = await ShareFileClient.Items.Stream(sfItem.GetObjectUri(true)).ExecuteAsync();

// Delete all but the latest version
foreach (var child in versions.Feed.Skip(1))
{
    await ShareFileClient.Items.Delete(child.url).ExecuteAsync();
}
```
