### ISSUE TITLE
How do you use a DI logger from Core?

### ISSUE THREAD

**Issue by pduer** [citrix/ShareFile-NET#39]
I see how the line:         configuration.Logger = new DefaultLoggingProvider(); works

But what if I want to provide my standard logger that I have DI to the Sharefile Client?

**Comment by NickNichollsCitrix** [comment]
Can you modify your logger to implement `ShareFile.Api.Client.Logging.ILogger`?
You could then pass in your logger like `configuration.Logger = customLogger;`

Alternatively, you could write some wrapper that implements `ShareFile.Api.Client.Logging.ILogger` and proxies calls to your custom logger.
Then pass it in like above, `configuration.Logger = wrapper;`

**Comment by pduer** [comment]
Yeah, after I typed this out I just caught on to that. I need to implment the Sharefile ILogger. 

I did that and it works good.
