### ISSUE TITLE
Missing PlatformFileStream?

### ISSUE THREAD

**Issue by pduer** [citrix/ShareFile-NET#40]
The readme documentation has the following line under the upload section:

`   var uploader = client.GetAsyncFileUploader(uploadRequest,
      new PlatformFileStream(file, file.Length, file.Name));`

However, that type is not found with the API referenced. Does it come form a different source?

**Comment by NickNichollsCitrix** [comment]
Oh, we ended up removing that type, but never updated the readme. I'll fix that.

You can use `var uploader = sfClient.GetAsyncFileUploader(uploadRequest, file);` instead

**Comment by pduer** [comment]
yeah found another post stating that! Thanks for the help!
