### ISSUE TITLE
Can passwords for Client Accounts be changed via the API?

### ISSUE THREAD

**Issue by pduer** [citrix/ShareFile-NET#42]
Is it possible to change a password of a Client Account in ShareFile using the API?

If it is, can the Client Account itself change it's own password if so granted those rights?

**Comment by NickNichollsCitrix** [comment]
Yes and yes.

To reset a password:
```
ODataObject request = new ODataObject();
request.AddProperty("OldPassword", oldPassword);
request.AddProperty("NewPassword", newPassword);
await SFClient.Users.ResetPassword(clientUser.url, request).ExecuteAsync();
```

If the client needs to do it, they will need the role `CanChangePassword`, which you should be able to update like:
```
await SFClient.Users.UpdateRoles(clientUser.url, new User { Roles = new List<UserRole>() { UserRole.CanChangePassword } }).ExecuteAsync();
```

**Comment by pduer** [comment]
Thanks!
