### ISSUE TITLE
Error updating the file retention policy

### ISSUE THREAD

**Issue by FRules** [citrix/ShareFile-NET#9]
I've had the following code working for quite a while:

```vb
Dim folderName = "BE-1005-0"

Dim folder = IsFolderExisting(sfClient, parentFolder, folderName).Result

If folder Is Nothing Then
    Dim folderNew= New Folder()
    folderNew.Name = folderName
    folder = CType(Await sfClient.Items.CreateFolder(parentFolder.url, folderNew, overwrite:=False).ExecuteAsync(), Folder)
End If

folder.ExpirationDate = DateTime.Now.AddDays(10)
Await sfClient.Items.Update(folder.url, folder).ExecuteAsync()

Return folder
```

When it comes to updating the folder with the expiration date, I get the following exception:

`{"There was an error updating the file retention policy. (HttpStatusCode: InternalServerError)"}`

Strange thing is it did update the expiration date. So as a workaround i do this in my catch-block:

```vb
...
     Return folder
     Catch ex As Exception
         Try
             Dim folderName = "BE-1005-0"

             Dim folder = IsFolderExisting(sfClient, parentFolder, bestellFolderName).Result

             If folder Is Nothing Then
                 Throw New Exception("Could not find sharefile folder")
             End If

             If folder.ExpirationDate = DateTime.MaxValue Then
                 Throw New Exception("Could not update expiration date")
             End If

             Return folder
         Catch exp As Exception
             ....
```

I do not want to be that a permanent solution though. As far as I know there wasn't a change in our sharefile-infrastructure. What can I do to fix this behaviour?

**Comment by rgmills** [comment]
Hi @FRules thanks for bringing this up.  There was a hotfix last night around some retention issues, I haven't had a change to dig in yet to see if the issue you are experiencing was resolved as a side effect yet or not.  I'll hopefully take a look tonight and let you know.

Until then, retention policies are controlled by the root-level folder.  For a folder path such as:

`\Clients\Robert Mills\2015 Taxes`

The Clients folder would control the retention policy for all of it's child folders.

Thanks again for bringing this up!

**Comment by rgmills** [comment]
Hi @FRules - I haven't been able to reproduce the issue you were experiencing.  Would you be able to verify the same?  Thanks.

**Comment by rgmills** [comment]
Hi @FRules - going to close this open, please reopen if you encounter it again.
